DROP TABLE IF EXISTS `report_execution`;
CREATE TABLE IF NOT EXISTS `report_execution` (
  `REPORT_EXECUTION_ID` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `REPORT_ID` int(11) unsigned NOT NULL,
  `EXECUTION_CONTENT_TYPE` enum('PDF','HTML','DOCX','XLS') NOT NULL DEFAULT 'PDF',
  `LAST_RUN_USER` int(11) unsigned NOT NULL,
  `STATUS` enum('QUEUED','IN_PROGRESS','FAILED','SUCCESSFUL') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'QUEUED',
  `DISPLAY_MESSAGE` varchar(500),
  `DETAIL_MESSAGE` text,
  `CREATED_BY` int(11) unsigned NOT NULL,
  `UPDATED_BY` int(11) unsigned NOT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_ON` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REPORT_EXECUTION_ID`),
  KEY `FK_REPORT_EXECUTION_REPORT` (`REPORT_ID`),
  KEY `FK_REPORT_EXECUTION_EMPLOYEE_MASTER` (`LAST_RUN_USER`),
  CONSTRAINT `FK_REPORT_EXECUTION_EMPLOYEE_MASTER1` FOREIGN KEY (`LAST_RUN_USER`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EXECUTION_EMPLOYEE_MASTER2` FOREIGN KEY (`CREATED_BY`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EXECUTION_EMPLOYEE_MASTER3` FOREIGN KEY (`UPDATED_BY`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EXECUTION_REPORT` FOREIGN KEY (`REPORT_ID`) REFERENCES `report` (`REPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



DROP TABLE IF EXISTS `report_email_tracker`;
CREATE TABLE IF NOT EXISTS `report_email_tracker` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `REPORT_ID` int(10) unsigned NOT NULL,
  `MANAGER_ID` int(10) unsigned NOT NULL,
  `EMPLOYEE_MASTER_ID` int(10) unsigned NOT NULL,
  `STATUS` enum('QUEUED','IN_PROGRESS','FAILED','SUCCESSFUL') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'QUEUED',
  `DISPLAY_MESSAGE` varchar(500),
  `DETAIL_MESSAGE` text,
  `CREATED_BY` int(11) unsigned NOT NULL,
  `UPDATED_BY` int(11) unsigned NOT NULL,
  `CREATED_ON` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LAST_SENT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_REPORT_EMAIL_TRACKER_EMPLOYEE_MASTER1` FOREIGN KEY (`MANAGER_ID`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EMAIL_TRACKER_EMPLOYEE_MASTER2` FOREIGN KEY (`EMPLOYEE_MASTER_ID`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EMAIL_TRACKER_EMPLOYEE_MASTER3` FOREIGN KEY (`CREATED_BY`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EMAIL_TRACKER_EMPLOYEE_MASTER4` FOREIGN KEY (`UPDATED_BY`) REFERENCES `employee_master` (`EMPLOYEE_MASTER_ID`),
  CONSTRAINT `FK_REPORT_EMAIL_TRACKER_REPORT` FOREIGN KEY (`REPORT_ID`) REFERENCES `report` (`REPORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;